services:
  - type: web
    name: backend-service
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    autoDeploy: true

  - type: web
    name: frontend-service
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    plan: free
    autoDeploy: true
