services:
  - type: web
    name: workout-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    autoDeploy: true

  - type: web
    name: workout-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist
    plan: free
    autoDeploy: true
